# Generated by Django 3.0.8 on 2020-11-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
