# Generated by Django 3.0.8 on 2020-11-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='concurrency',
            field=models.IntegerField(default=3),
        ),
    ]
