# Generated by Django 3.0.8 on 2020-11-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_userprofile_concurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture_url',
            field=models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRThY_01nTnP3fP1WlRQrF45q43HGU5O2PwjA&usqp=CAU', null=True),
        ),
    ]
