# Generated by Django 3.0.8 on 2020-11-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_keyword_report_userreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='crawled_links',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recent_link',
            field=models.IntegerField(default=5),
        ),
    ]
