# Generated by Django 3.0.8 on 2020-11-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_auto_20201121_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='predicted',
        ),
        migrations.AddField(
            model_name='report',
            name='predicted_data',
            field=models.TextField(blank=True, default='{"News_Authenticity": "92%", "Accuracy Score": "95%"}', max_length=3000),
        ),
    ]
